### ISSUE TITLE
USB_MTPDISK_MIDI

### ISSUE THREAD

**Issue by MaurinElectroTextile** [KurtE/MTP_Teensy#14]
Dear Kurt,
I'm trying to add USB_MTPDISK_MIDI interface to my project.
I'm using Platformio with the last PaulStoffregen/cores from github, and your MTP_Teensy library. 
Considering the explanations in the file /cores/teensy4/usb_desc.h I added to it the flowing content:

```
#elif defined(USB_MTPDISK_MIDI)
  #define VENDOR_ID                0x16E0
  #define PRODUCT_ID		  0x03D1
  #define MANUFACTURER_NAME	      {'T','e','e','n','s','y','d','u','i','n','o'}
  #define MANUFACTURER_NAME_LEN	  11
  #define PRODUCT_NAME		        {'T','e','e','n','s','y',' ','M','T','P',' ','M','I','D','I'}
  #define PRODUCT_NAME_LEN	      15
  #define EP0_SIZE		            64
  #define NUM_ENDPOINTS           5
  #define NUM_INTERFACE           3
  #define MTP_INTERFACE		        3   /* MTPDISK */
  #define MTP_TX_ENDPOINT	        4
  #define MTP_TX_SIZE_12	        64
  #define MTP_TX_SIZE_480	        512
  #define MTP_RX_ENDPOINT	        4
  #define MTP_RX_SIZE_12	        64
  #define MTP_RX_SIZE_480	        512
  #define MTP_EVENT_ENDPOINT	    5
  #define MTP_EVENT_SIZE	        32
  #define MTP_EVENT_INTERVAL_12	  10
  #define MTP_EVENT_INTERVAL_480  7
  #define SEREMU_INTERFACE        2	  /* SERIAL_EMULATION */
  #define SEREMU_TX_ENDPOINT      2
  #define SEREMU_TX_SIZE          64
  #define SEREMU_TX_INTERVAL      1
  #define SEREMU_RX_ENDPOINT      2
  #define SEREMU_RX_SIZE          32
  #define SEREMU_RX_INTERVAL      2
  #define MIDI_INTERFACE	        1	  /* MIDI */
  #define MIDI_NUM_CABLES	        1
  #define MIDI_TX_ENDPOINT	      3
  #define MIDI_TX_SIZE_12	        64
  #define MIDI_TX_SIZE_480	      512
  #define MIDI_RX_ENDPOINT	      3
  #define MIDI_RX_SIZE_12	        64
  #define MIDI_RX_SIZE_480	      512
  #define ENDPOINT2_CONFIG	      ENDPOINT_RECEIVE_INTERRUPT + ENDPOINT_TRANSMIT_INTERRUPT
  #define ENDPOINT3_CONFIG	      ENDPOINT_RECEIVE_BULK + ENDPOINT_TRANSMIT_BULK
  #define ENDPOINT4_CONFIG	      ENDPOINT_RECEIVE_BULK + ENDPOINT_TRANSMIT_BULK
  #define ENDPOINT5_CONFIG	      ENDPOINT_RECEIVE_UNUSED + ENDPOINT_TRANSMIT_INTERRUPT
```
Then as you did for USB_MTPDISK, I added some changes to the cores/teensy4/usb.c
Add
`#if defined(USB_MTPDISK) || defined(USB_MTPDISK_SERIAL) || (USB_MTPDISK_MIDI)`
src/MTP_Teensy.h
Add
`#if !defined(USB_MTPDISK) && !defined(USB_MTPDISK_SERIAL) && !defined(USB_MTPDISK_MIDI)`
src/MTP_Teensy.cpp
Add
`#if defined(USB_MTPDISK) || defined(USB_MTPDISK_SERIAL) || defined(USB_MTPDISK_MIDI)`
Remove
`#include <MemoryHexDump.h>`

ALL IS WORKING PROPERLY ;-)

**Comment by KurtE** [comment]
Sorry, 

I am not sure this is the right github project to raise this issue against:

It is more an issue for @PaulStoffregen  in the cores project as well as the Arduino IDE stuff (boards.txt)

I also don't use platform IO much... So not sure of the setup.  For example with our current sources: MTP_Teensy.cpp has
```
Stream *MTPD::printStream_ = &Serial;
```
I know there are several questions on how best to handle all of the different USB types and combinations. 
And it is my impression that this won't be changed much in the short term.    I know there has been an outstanding request from the original MTPD stuff (WMXZ) to add MTP plus Serial... And he has in his library the things that needed to change to support it.  Problem is they may not be fully updated as the sources evolve. 

Also with the T4x boards the USB hardware has less endpoints that you can define, so unlike the T3.x which has the kitchen sink USB type (everything or all of the above) that can not be defined on T4.x 

Good luck
