### ISSUE TITLE
sprintf into array of char

### ISSUE THREAD

**Issue by FrankBoesing** [KurtE/MTP_Teensy#19]
[https://github.com/KurtE/MTP_Teensy/blob/d458bbc300e35ba3412812fdd4238a2c8929b4f1/src/MTP_Storage.cpp#L460](https://github.com/KurtE/MTP_Teensy/blob/d458bbc300e35ba3412812fdd4238a2c8929b4f1/src/MTP_Storage.cpp#L460)

... is likely to overflow. better use snprintf, everywhere

**Comment by KurtE** [comment]
Thanks, I thought we had replaced all of them, but... 

Pushed up a change

**Comment by FrankBoesing** [comment]
thanks :)
