### ISSUE TITLE
Serial not working on Platform IO project build

### ISSUE THREAD

**Issue by david-res** [KurtE/MTP_Teensy#37]
When including MTP_Teensy on a PIO teensy project and setting the build flags as required by the library, there is no output on the serial monitor (PIO serial monitor as well as Teensyduino IDE serial monitor)
The teensy only appears as` HID: Teensy MTP` and does not appear in the Serial list on Teensyduino IDE available devices

Build flags in PIO are set up like so:
`
[env:teensymm]
platform = teensy
board = teensymm
framework = arduino
build_flags = -D TEENSY_OPT_SMALLEST_CODE -D USB_MTPDISK -D USB_MTPDISK_SERIALL
board_build.f_cpu = 396000000L
`

**Comment by KurtE** [comment]
Note: MTP_Teensy does not control if you have Serial or not, those are controlled by the CORE. 
However,  MTP_Teensy does rely on which USB Flags you use as it requires that the MTP USB descriptor is in place.

There are Two configurations that work for MTP

USB_MTPDISK - Which defined MTP plus it has SEREMU for serial output.

USB_MTPDISK_SERIAL - which defines MTP plus Serial

Note: You don't define both in your build and in the case USB_MTPDISK has priority as in usb_desc.h we have:
```
#elif defined(USB_MTPDISK)
<defines for this>
#elif defined(USB_MTPDISK_SERIAL)
<defines for this>
...
```

Note:  you show USB_MTPDISK_SERIALL
(With two L's)

**Comment by david-res** [comment]
@KurtE thanks for the explanation.
I set the build flag to USB_MTPDISK and that seems to include the relevant defines for USB_MTPDISK in **usb_dsc.h**
But for some reason if I set USB_MTPDISK_SERIAL, it doesn't include the defines for USB_MTPDISK_SERIAL.
I will keep playing around with it, but it just might be a PIO issue, so I'll take it with them if this persists

**Comment by KurtE** [comment]
Maybe Platform IO has not yet been updated to include Serial + MTP Disk.

This option was only added in Teensyduino 1.57 as you will see in the release notes:
https://forum.pjrc.com/threads/70740-Teensyduino-1-57-Released

Actually, it was added in some of the beta builds... But it was not back in 1.56

Simply check your usb_desc.h file and if it does not have a check for it as the elif like I mentioned, then your version has been updated to support it yet.  Long before now, we were manually adding it in to the system by adding the defines, but
finally, it is actually in and it has an official PID.  Before it was hacked in using the everything PID...

**Comment by david-res** [comment]
I found the issue, it was a missing USD flag in the PIO Teensy-Arduino framework.
I added in USB_MTPDISK_SERIAL to the list and it compiles and works now - I've opened an issue on their [git ](https://github.com/platformio/platform-teensy/issues/91)
I'll close the issue here. Thanks!
