### ISSUE TITLE
Question: Should this work on a Teensy LC?

### ISSUE THREAD

**Issue by JaySmith** [KurtE/MTP_Teensy#40]
I am trying to create the Audio Guestbook with the old phone.  I purchased a Teensy LC by mistake and time is running out.  

When I compile I get several errors for :usb_mtp_status not declared

**Comment by KurtE** [comment]
Note: Better to ask these questions on the forum,

Simple answer is, I am not sure. @PaulStoffregen @mjs513  ?

Sorry I am not on my main machine, on Ubuntu test machine.

But if I edit the sources and add it to the couple of #if in MTP_Teensy.h/.cpp
like:
```
#if defined(__MK20DX128__) || defined(__MK20DX256__) ||                        \
    defined(__MK64FX512__) || defined(__MK66FX1M0__) ||                        \
    defined(__MKL26Z64__)
```
2 places in .cpp 1 in .h

It mostly builds.  But even the most simple SD example, then currently fails to link,
```
/home/kurte/.arduino15/packages/teensy/tools/teensy-compile/11.3.1-beta1/arm/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 6016 bytes
/home/kurte/.arduino15/packages/teensy/tools/teensy-compile/11.3.1-beta1/arm/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld: region `RAM' overflowed by 4748 bytes
collect2: error: ld returned 1 exit status
```
Not enough memory.  So would need to go through and see what things could be stripped..

And probably a lot would need to be fixed up to make room for the Audio Guestbook which probably needs a lot more space.

**Comment by JaySmith** [comment]
Thanks for the reply, didn't know where the forum was. First time user and in a panic :-/  Think this is going to have to go on the shelf and order a Teensy proper.

Thanks again.
