### ISSUE TITLE
Error in Arduino IDE after compiling

### ISSUE THREAD

**Issue by Johnnyyr** [KurtE/MTP_Teensy#42]
Hello,

i have a problem after compiling your code, i use the 4.1 with the Audio shield. Can you help me somehow?

Arduino IDE 2.0.2
MPT_Teensy: https://github.com/KurtE/MTP_Teensy (the same error with the original)

This is what i got:

c:\Users\xxxxxxxxx\Privat\Dokumente\Arduino\libraries\MTP_Teensy-main\src\MTP_Teensy.cpp: In member function 'uint32_t MTP_class::GetObjectInfo(MTP_class::MTPContainer&)':
c:\Users\xxxxxxxx\Dokumente\Arduino\libraries\MTP_Teensy-main\src\MTP_Teensy.cpp:523:34: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
   #pragma GCC diagnostic ignored "-Wformat-truncation" /* Or "-Wformat-truncation" */
                                  ^
Opening Teensy Loader...
Memory Usage on Teensy 4.1:
  FLASH: code:110912, data:14636, headers:8592   free for files:7992324
   RAM1: variables:19264, code:107352, padding:23720   free for local variables:373952
   RAM2: variables:45440  free for malloc/new:478848

**Comment by KurtE** [comment]
Note: It is just a warning, so hopefully is not stopping anything. 

What version of Teensyduino are you using?  the Released 1.57 one or the Beta 1.58b2? or???

That is I am I not seeing that warning, but I am running the beta build which is using the new compiler.

**Comment by KurtE** [comment]
Going to go ahead and close this one for now.
