### ISSUE TITLE
Question - How does MTP interact with Mac?  Similar to linux?

### ISSUE THREAD

**Issue by spenceriam** [KurtE/MTP_Teensy#43]
I wanted to know if this code can also support Mac.  I imagine it might be similar to Linux, but I wanted to know.  Do we need to manually mount on Mac then perhaps?  Any thoughts?

**Comment by PaulStoffregen** [comment]
Use Android File Transfer

https://www.android.com/filetransfer/

**Comment by KurtE** [comment]
Sorry I am not much of a MAC user.  I do have an older MAC Book pro that I do some testing on. 

I also mainly use the android app that Paul mentioned.  

Earlier I tried an app I think called openMTP, but the free version was really limited.  Did not purchase their main version.

Recently on some thread on PJRC forum, I remember someone mentioning that they use something else, but I don't remember which thread..  

Actually probaby this one: https://forum.pjrc.com/threads/68139-Teensyduino-File-System-Integration-including-MTP-and-MSC?p=322555&viewfull=1#post322555

There are posts before it as well

**Comment by spenceriam** [comment]
@KurtE I appreciate the link.  I should have checked the forums, my apologizes.  I'll give Android file transfer a try.  In case you're wondering I'm using this on Audio Guestbook project that PlayfulTechnology put together last year.  I was brave enough to make my own tweaks to add additional functionality.  However, I failed to realize that not everyone owns a Windows based PC.  Thanks for the assistance on this.

**Comment by PaulStoffregen** [comment]
Android File Transfer is as good as it gets (for free) on MacOS.  I also haven't tried the paid program.

It's obviously not as integrated with MacOS Finder as MTP is with Windows Explorer.  But it is pretty easy to use.
